- hosts: all
  remote_user: vagrant
  become: yes
  tasks:
          - name: Ajustando o TimeZone do Servidor
            timezone:
                    name: America/Sao_Paulo
- hosts: db
  remote_user: vagrant
  become: yes
  tasks:
          - name: Criando o Arquivo Info
            lineinfile:
                    path: /tmp/info
                    line: SERVIDOR DE BANCO DE DADOS MYSQL
                    create: yes
          - name: Definindo a Senha de Administrador do MySQL
            debconf: name='mysql-server' question='mysql-server/root_password' value='123' vtype='password'

          - name: Confirmando a Senha de Administrador do MySQL
            debconf: name='mysql-server' question='mysql-server/root_password_again' value='123' vtype='password'          

          - name: Instalando mysql server
            apt:
                    state: present
                    update_cache: yes
                    pkg:
                    - mysql-server
                    - python-pymysql
                      
          - name: Criando banco de dados para wordpress
            mysql_db:
                    name: wordpress
                    state: present
                    login_user: root
                    login_password: 123
          - name: Criando o usuario do banco
            mysql_user:
                    name: wordpress
                    password: impacta
                    priv: '*.*:ALL'
                    state: present
                    host: 172.17.177.22
                    login_user: root
                    login_password: 123
          - name: Configurando bind MySQL
            lineinfile:
                    path: /etc/mysql/mysql.conf.d/mysqld.cnf
                    regexp: '^bind-address'
                    line: bind-address = 0.0.0.0
                    notify:
                            - restart mysql
                    handlers:
                            - name: restart mysql
                              service:
                                      name: mysql
                                      state: restarted
- hosts: web
  remote_user: vagrant
  become: yes
  tasks:
          - name: Criando o Arquivo Info
            lineinfile:
                    path: /tmp/info
                    line: SERVIDOR DO BLOG WORDPRESS
                    create: yes
          - name: Instalando Apache
            apt:
                    name: apache2
                    state: present
          - name: Instalando dependencias
            apt:
                    pkg:
                            - php7.2
                            - php7.2-mysql
                            - libapache2-mod-php7.2
                            - php7.2-cli
                            - php7.2-cgi
                            - php7.2-gd
                            - apache2-utils
                            - mysql-client
                    state: present
          - name: enable service apache2
            systemd:
                    name: apache2
                    enabled: yes
                    masked: no
          - name: start apache2
            systemd:
                    state: started
                    name: apache2
- hosts: engine
  remote_user: vagrant
  become: yes
  tasks:
          - name: Criando o Arquivo Info
            lineinfile:
                    path: /tmp/info
                    line: SERVIDOR ANSIBLE CONTROLLER
                    create: yes
